// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOooDzoRGGJO8EjOlxcdEuJ0oRsgaLvXY',
    appId: '1:322989721241:web:b506b452f91a51d3fdda08',
    messagingSenderId: '322989721241',
    projectId: 'flutter-authentication-form',
    authDomain: 'flutter-authentication-form.firebaseapp.com',
    storageBucket: 'flutter-authentication-form.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcBXEfP-RKx0lKgsUkuCWH5og-LPSF3Ds',
    appId: '1:322989721241:android:0d3b5ee2a1975672fdda08',
    messagingSenderId: '322989721241',
    projectId: 'flutter-authentication-form',
    storageBucket: 'flutter-authentication-form.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXMs6MXsEZGZxXO_eGLwshbSptT6GSOao',
    appId: '1:322989721241:ios:a453308c86f5cf5ffdda08',
    messagingSenderId: '322989721241',
    projectId: 'flutter-authentication-form',
    storageBucket: 'flutter-authentication-form.appspot.com',
    iosClientId: '322989721241-ebblf2q73qn9ilntdg9hdvo5urlcl678.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterSigninForm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXMs6MXsEZGZxXO_eGLwshbSptT6GSOao',
    appId: '1:322989721241:ios:a453308c86f5cf5ffdda08',
    messagingSenderId: '322989721241',
    projectId: 'flutter-authentication-form',
    storageBucket: 'flutter-authentication-form.appspot.com',
    iosClientId: '322989721241-ebblf2q73qn9ilntdg9hdvo5urlcl678.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterSigninForm',
  );
}
